# Generated by Django 3.0.7 on 2020-06-24 15:40

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('capital', models.IntegerField()),
                ('initial_stocks', models.IntegerField()),
                ('agent_type', models.IntegerField()),
                ('progress', models.IntegerField()),
                ('graph_data', picklefield.fields.PickledObjectField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StockApp.User')),
            ],
        ),
    ]
